### ISSUE TITLE
Apple privacy manifest support

### ISSUE THREAD

**Issue by pavm035** [rakuten-ads/Rakuten-Ads-iOS#33]
Hi,

According to apple news to support privacy manifest and signing for the SDK, we would like to know the support from this SDK since deadline is May 1st, and apps which are dependent on this SDK will have impact

We understand that v1.15.0 supports manifest, but we want to know code signing part

https://developer.apple.com/news/?id=3d8a9yyh
https://developer.apple.com/support/third-party-SDK-requirements/

**Comment by wei-b-wu-rakuten** [comment]
Hi, thanks for the question.

To your concern, the current release of our SDK hasn't been code signed.
Since our SDK is not in the SDK list which Apple required, I don't think the deadline will impact us for now.
But the privacy manifest is supposed to have an significant impact on App submission so we dealt with it first in a hurry.

For code sign, we have planned to support it but have to take more time to prepare carefully as it could be saw as an certification of the whole organization and may impact future update.
We will get you informed in the future release.

**Comment by pavm035** [comment]
@wei-b-wu-rakuten  thanks for the quick response, yes we had same concern like you on targetting the not listed SDKs, but we got reply from apple that if you own the SDK then you must provide the manifest and signing support, i also found similar question in forum and one of the apple engineer mentioned the same

https://developer.apple.com/forums/thread/743650?answerId=776588022#776588022

**Comment by wei-b-wu-rakuten** [comment]
thank you very much for this first hand information, never heard.
I was taking the manifest is required for the Apple's app review so better everyone follow the rule.
but the signature is only base on the trust between app developer and SDK author.
Xcode 15 surely validates the signature but from the WWDC video clip the developer can also choose to accept it or not .

I guess maybe the reply of the forum link was trying to say that app developer has to sign all the unsigned dependencies.
I noticed there was a selection setting `embed and sign` when importing frameworks in old Xcode 14 before but had disappeared now in Xcode 15.

Let me do some further investigation and then give you a reply.

**Comment by pavm035** [comment]
@wei-b-wu-rakuten  Thanks for understanding and any updates?

**Comment by wei-b-wu-rakuten** [comment]
Yeah, soon we are gonna release a new version which is code signed with our developer team's certification.

**Comment by pavm035** [comment]
@wei-b-wu-rakuten Any updates on release?

**Comment by wei-b-wu-rakuten** [comment]
@pavm035 new version 1.15.1 with code sign released.
please confirm.
https://github.com/rakuten-ads/Rakuten-Ads-iOS/releases/tag/1.15.1

**Comment by wei-b-wu-rakuten** [comment]
@pavm035 Hi, we have released a new version 1.15.2 by changed to a more appropriate certificate for signing.
I recommend that you update it.

**Comment by pavm035** [comment]
@wei-b-wu-rakuten  Is it a big change our QA verification almost done?

**Comment by wei-b-wu-rakuten** [comment]
No codes updated, only version number & signing, so I don't think so.

Just next time when you update SDK, 
Xcode will alert you that the signature got changed, needs your confirmation to accept change.

**Comment by pavm035** [comment]
Ok thnaks for the infox
