### ISSUE TITLE
Cannot build with V1.16.0

### ISSUE THREAD

**Issue by jeongwoolee-rakuten** [rakuten-ads/Rakuten-Ads-iOS#41]
V1.16.0 cannot be built with this error.
Missing path (XXXXXXX/SourcePackages/artifacts/rakuten-ads-ios/RUNACore/RUNACore.xcframework/ios-arm64_x86_64-simulator/dSYMs) from XCFramework 'RUNACore.xcframework' as defined by 'DebugSymbolsPath' in its `Info.plist` file

V1.15.2 can be done successfully.

**Comment by wei-b-wu-rakuten** [comment]
OK, I see the problem.
May I known your Xcode version?

**Comment by wei-b-wu-rakuten** [comment]
We will release a new version to fix this issue.
I will let you known when it is ready.

**Comment by wei-b-wu-rakuten** [comment]
We have fixed this issue by removing the `DebugSymbolsPath` declared in the Info.plist.
please update to version `1.16.1`.
